-- local config = {
--     cmd = {'/usr/local/Cellar/jdtls/1.30.1'},
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- require('jdtls').start_or_attach(config)
